language: python
install: pip install pycodestyle
jobs:
  include:
    - stage: test
      name: "Linting with pycodestyle"
      python: "3.6"
      script:
        - find . -name \*.py -exec pycodestyle {} +