language: python
python:
  - "3.6"
# pycodestyle is the new name of pep8
install: pip install pycodestyle homeassistant
script:
  - find . -name \*.py -exec pycodestyle {} +
  - hass -c . --script check_config
  - ls
  - hass -c . --daemon
  - wait 10
  - cat ./home-assistant-log
  - ls
